TestSignedIsNegative:               JSR SignedIsNegative
TestDivide:                         JSR Divide
TestMultiply:                       JSR Multiply
TestAccumulateLong:                 JSR AccumulateLong
TestSignedIncrease:                 JSR SignedIncrease
TestSignedDecrease:                 JSR SignedDecrease
TestMultiplyLong:                   JSR MultiplyLong
TestAddLong:                        JSR AddLong
TestMovePlayer:                     JSR MovePlayer
TestTilesOverlap:                   JSR TilesOverlap
TestPlayerCollision:                JSR PlayerCollision
